version: 2.1
deploy:
  description: Deploy to firebase
  parameters:
    token:
      type: string
      description: Firebase Deploy Token
  steps:
    - run:
        name: Install Firebase Tools
        command: npm install firebase-tools
    - run:
        name: Deploy
        command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive